version: '3'

services:
  web:
    image: abiosoft/caddy:no-stats
    ports:
      - 5555:5555
    volumes:
      - ./caddy/Caddyfile:/etc/Caddyfile
      - ./caddy/index.html:/srv/index.html
      - caddy_data:/root/.caddy
    env_file: .env
  obs:
    build: ./obs
    volumes:
      - ./config:/config
  remote:
    build:
      context: ./remote
      args:
        - homepage=/remote
  rtmp:
    image: tiangolo/nginx-rtmp
    ports:
      - 1935:1935
    volumes:
      - ./rtmp/nginx.conf:/etc/nginx/nginx.conf

volumes:
  caddy_data: