version: '3'

services:
  web:
    restart: unless-stopped
    image: abiosoft/caddy:no-stats
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/Caddyfile
      - ./caddy/public:/srv
      - ./config/caddy:/root/.caddy
    environment:
      - DOMAIN=${DOMAIN}
      - AUTH_USER=${AUTH_USER}
      - AUTH_PASS=${AUTH_PASS}

  obs:
    restart: unless-stopped
    build: ./obs
    volumes:
      - ./config/obs:/config/xdg/config/obs-studio
      - ./config/user:/config/user
  remote:
    restart: unless-stopped
    build:
      context: ./remote
      args:
        - homepage=/remote
  rtmp:
    restart: unless-stopped
    build: ./rtmp
    command: /app/start.sh
    ports:
      - 1935:1935
    environment:
      - AUTH_USER=${AUTH_USER}
      - AUTH_PASS=${AUTH_PASS}

  duckdns:
    restart: unless-stopped
    image: linuxserver/duckdns
    environment:
      - SUBDOMAINS=${DUCKDNS_SUBDOMAIN}
      - TOKEN=${DUCKDNS_TOKEN}
  netdata:
    restart: unless-stopped
    image: netdata/netdata
    hostname: ${DOMAIN}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DO_NOT_TRACK=1
      - DOCKER_HOST=docker-proxy:2375
    depends_on:
      - docker-proxy
  docker-proxy:
    restart: unless-stopped
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
