version: '3'

services:
  web:
    image: abiosoft/caddy:no-stats
    ports:
      - 5555:5555
    volumes:
      - ./caddy/Caddyfile:/etc/Caddyfile
      - caddy_data:/root/.caddy
  obs:
    build: ./obs
    volumes:
      - ./config:/config
    environment:
      - VNC_PASSWORD=monsec_live
  remote:
    build:
      context: ./remote
      args:
        - homepage=/remote
  rtmp:
    image: tiangolo/nginx-rtmp
    ports:
      - 1935:1935

volumes:
  caddy_data: