version: '3'

services:
  web:
    restart: unless-stopped
    image: abiosoft/caddy:no-stats
    ports:
      - 5555:5555
    volumes:
      - ./caddy/Caddyfile:/etc/Caddyfile
      - ./caddy/index.html:/srv/index.html
      - caddy_data:/root/.caddy
    env_file: .env

  obs:
    restart: unless-stopped
    build: ./obs
    volumes:
      - ./config:/config
  remote:
    restart: unless-stopped
    build:
      context: ./remote
      args:
        - homepage=/remote
  rtmp:
    restart: unless-stopped
    image: tiangolo/nginx-rtmp
    ports:
      - 1935:1935
    volumes:
      - ./rtmp/nginx.conf:/etc/nginx/nginx.conf

  netdata:
    restart: unless-stopped
    image: netdata/netdata
    hostname: ${CS_DOMAIN}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DO_NOT_TRACK=1
      - DOCKER_HOST=docker-proxy:2375
    depends_on:
      - docker-proxy
  docker-proxy:
    restart: unless-stopped
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1

volumes:
  caddy_data: